export { MonicaApiClient, type MonicaApiClientOptions } from "./client.js";
export {
	MonicaApiError,
	MonicaNetworkError,
	MonicaPaginationCapError,
} from "./errors.js";
export type { StructuredLogger } from "./logger-interface.js";
export { type PaginatedResponsePage, type PaginateOptions, paginateAll } from "./pagination.js";
export {
	AccountRef,
	Activity,
	ActivityType,
	ActivityTypeCategory,
	Address,
	Avatar,
	ContactField,
	ContactFieldType,
	Country,
	CreateActivityRequest,
	CreateAddressRequest,
	CreateContactFieldRequest,
	CreateContactRequest,
	CreateNoteRequest,
	CreateRelationshipRequest,
	CreateReminderRequest,
	DeleteResponse,
	EmbeddedContact,
	ErrorResponse,
	FrequencyType,
	FullContact,
	Gender,
	MonicaDateField,
	Note,
	PaginatedResponse,
	PaginationLinks,
	PaginationMeta,
	PaginationMetaLink,
	Relationship,
	RelationshipShort,
	RelationshipType,
	RelationshipTypeGroup,
	Reminder,
	ReminderOutbox,
	Tag,
	UpdateContactCareerRequest,
	UpdateRelationshipRequest,
} from "./schemas/index.js";
export { type RetryOptions, withRetry, withTimeout } from "./transport.js";
