/**
 * Drizzle schema for the ai-router service.
 *
 * Table ownership: All tables in this file are owned by ai-router.
 * No other service should read or write these tables directly.
 */

import { sql } from "drizzle-orm";
import { index, integer, jsonb, pgTable, text, timestamp, unique, uuid } from "drizzle-orm/pg-core";

/**
 * Conversation turns table.
 * Stores compressed turn summaries for multi-turn conversation context.
 * Only compressed summaries are stored -- never raw utterances or full LLM responses.
 *
 * user_id references users in user-management's table but has no FK constraint
 * because it is a cross-service reference. Application-level validation suffices for V1.
 */
export const conversationTurns = pgTable(
	"conversation_turns",
	{
		id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
		userId: uuid("user_id").notNull(),
		role: text("role").notNull(),
		summary: text("summary").notNull(),
		correlationId: text("correlation_id").notNull(),
		createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
	},
	(table) => [
		index("idx_conversation_turns_user_created").on(table.userId, table.createdAt.desc()),
		index("idx_conversation_turns_created_at").on(table.createdAt),
	],
);

/**
 * Pending commands table.
 * Stores commands generated by the AI pipeline that require user confirmation
 * before execution. Only mutating commands enter this lifecycle.
 *
 * user_id references users in user-management's table but has no FK constraint
 * because it is a cross-service reference. Application-level validation suffices for V1.
 */
export const pendingCommands = pgTable(
	"pending_commands",
	{
		id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
		userId: uuid("user_id").notNull(),
		commandType: text("command_type").notNull(),
		payload: jsonb("payload").notNull(),
		status: text("status").notNull().default("draft"),
		version: integer("version").notNull().default(1),
		/**
		 * Connector-neutral opaque string identifying the originating message.
		 * Format is determined by the connector (e.g. "telegram:msg:12345").
		 * Other services must not parse or interpret this value.
		 */
		sourceMessageRef: text("source_message_ref").notNull(),
		correlationId: text("correlation_id").notNull(),
		createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
		expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
		confirmedAt: timestamp("confirmed_at", { withTimezone: true }),
		executedAt: timestamp("executed_at", { withTimezone: true }),
		terminalAt: timestamp("terminal_at", { withTimezone: true }),
		executionResult: jsonb("execution_result"),
		/**
		 * Progressive narrowing state for contact disambiguation.
		 * Stores the narrowing context (candidate IDs, clarification terms, round)
		 * as a dedicated JSONB column to avoid violating the strict MutatingCommandPayload
		 * discriminated union in the payload column.
		 * Nullable -- only present during active narrowing.
		 */
		narrowingContext: jsonb("narrowing_context"),
		/**
		 * Deferred contact reference for confirm-then-resolve flow.
		 * When a mutating command has an unresolved contact reference, the system
		 * first confirms the ACTION with the user, then resolves the contact only
		 * after the user confirms. This avoids wasted disambiguation effort when
		 * the user wants to cancel or edit the action.
		 * Nullable -- only present when contact resolution has been deferred.
		 */
		unresolvedContactRef: text("unresolved_contact_ref"),
	},
	(table) => [
		index("idx_pending_commands_user_status").on(table.userId, table.status),
		index("idx_pending_commands_expires_at").on(table.expiresAt),
	],
);

/**
 * Conversation history table for the agent loop.
 * Stores the full OpenAI-format message array per user as JSONB,
 * plus an optional pending tool call for confirmation guardrails.
 * One row per user (upserted on each agent loop invocation).
 *
 * user_id references users in user-management's table but has no FK constraint
 * because it is a cross-service reference. Application-level validation suffices for V1.
 */
export const conversationHistory = pgTable(
	"conversation_history",
	{
		id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
		userId: uuid("user_id").notNull(),
		messages: jsonb("messages").notNull().default(sql`'[]'::jsonb`),
		pendingToolCall: jsonb("pending_tool_call"),
		updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
	},
	(table) => [
		unique("uq_conversation_history_user_id").on(table.userId),
		index("idx_conversation_history_updated_at").on(table.updatedAt),
	],
);
